name: Build

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: yarn install
            - run: yarn coverage

    dist:
        needs: [test]
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: samuelmeuli/action-snapcraft@v1
              if: ${{ matrix.os == 'ubuntu-latest' }}
            - run: yarn install
            - run: yarn release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
